/*
 * This source file was generated by the Gradle 'init' task
 */
package q6;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter a number: ");
        int num = sc.nextInt();
        sc.close();

        int fact = 1;
        System.out.println("Enter a number: " + num);
        for (int i = 1; i <= num; i++) {
            System.out.println(i + "! = " + fact);
            fact += fact * i;
        }
    }
}
