/*
 * This source file was generated by the Gradle 'init' task
 */
package q4;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Input value A: ");
        int a = sc.nextInt();
        System.out.print("Input value B: ");
        int b = sc.nextInt();
        System.out.print("Input value C: ");
        int c = sc.nextInt();
        sc.close();
        if (a >= b && a >= b) {
            System.out.println("Max value is A");
        } else if (b >= a && b >= c) {
            System.out.println("Max value is B");
        } else {
            System.out.println("Max value is C");
        }
    }
}
